import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "../components/NavBar/nav";
import StarsCanvas from "@/components/starsBack/stars";
import FooterSection from "@/components/footer/footer";
import { Providers } from "./providers";
import { ThemeSwitcher } from "@/components/ThemeSwitcher/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body>
        <Providers>
          <ThemeSwitcher />
          <StarsCanvas />
          <NavBar />
          {children}
          <FooterSection />
        </Providers>
      </body>
    </html>
  );
}
